import { initializeApp } from "https://www.gstatic.com/firebasejs/12.15.0/firebase-app.js";
import { getFirestore, collection, addDoc, deleteDoc, doc, onSnapshot, serverTimestamp, runTransaction } from "https://www.gstatic.com/firebasejs/12.15.0/firebase-firestore.js";

const firebaseConfig={apiKey:"AIzaSyDtxRZL_IWajJod__LC0QSIXffxDhuR9JY",authDomain:"control-de-ventas-60c55.firebaseapp.com",projectId:"control-de-ventas-60c55",storageBucket:"control-de-ventas-60c55.firebasestorage.app",messagingSenderId:"535636855570",appId:"1:535636855570:web:d990feac541dbd039481cb"};
const app=initializeApp(firebaseConfig), db=getFirestore(app);
const salesRef=collection(db,"ventas"),paymentsRef=collection(db,"pagos"),inventoryRef=collection(db,"inventario");
let sales=[],payments=[],inventory=[];let ready={sales:false,payments:false,inventory:false};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const page=document.body.dataset.page||"home";const today=new Date();const todayISO=toISODate(today),currentMonth=todayISO.slice(0,7);
function toISODate(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function money(v){return new Intl.NumberFormat("es-CR",{style:"currency",currency:"CRC",maximumFractionDigits:0}).format(Number(v||0)).replace("CRC","₡")}
function dateFmt(s){if(!s)return"";const[y,m,d]=s.split("-");return`${d}/${m}/${y}`}
function parseAmount(v){return Number(String(v??"").replace(/[^\d]/g,"")||0)}
function normName(n){return String(n||"").trim().replace(/\s+/g," ")}
function keyName(n){return normName(n).toLocaleLowerCase("es").normalize("NFD").replace(/[\u0300-\u036f]/g,"")}
function stamp(r){if(r.createdAt?.toMillis)return r.createdAt.toMillis();return new Date(`${r.date||"1970-01-01"}T12:00:00`).getTime()}
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function msg(el,text,error=false){if(!el)return;el.textContent=text;el.classList.toggle("error",error)}
function debtors(){const map=new Map();for(const s of sales){if(s.status!=="credit")continue;const k=s.clientKey||keyName(s.clientName);const x=map.get(k)||{clientKey:k,clientName:s.clientName,credit:0,paid:0,count:0};x.credit+=Number(s.amount||0);x.count++;map.set(k,x)}for(const p of payments){const k=p.clientKey||keyName(p.clientName);const x=map.get(k)||{clientKey:k,clientName:p.clientName,credit:0,paid:0,count:0};x.paid+=Number(p.amount||0);map.set(k,x)}return[...map.values()].map(x=>({...x,debt:Math.max(0,x.credit-x.paid)})).filter(x=>x.debt>0).sort((a,b)=>b.debt-a.debt||a.clientName.localeCompare(b.clientName,"es"))}
function monthLabel(k){const[y,m]=k.split("-").map(Number);const t=new Intl.DateTimeFormat("es-CR",{month:"long",year:"numeric"}).format(new Date(y,m-1,1));return t.charAt(0).toUpperCase()+t.slice(1)}
function allMovements(){return[...sales.map(x=>({...x,kind:"sale",sortTime:stamp(x)})),...payments.map(x=>({...x,kind:"payment",sortTime:stamp(x)}))].sort((a,b)=>b.sortTime-a.sortTime)}
function activeInventory(){return [...inventory].filter(x=>Number(x.quantity)>0).sort((a,b)=>a.name.localeCompare(b.name,"es"))}
function setStatus(){const el=$("#connectionStatus");if(el&&ready.sales&&ready.payments&&ready.inventory)el.textContent="● Sincronizado"}
function render(){if(page==="home")renderHome();if(page==="sale")renderSaleProducts();if(page==="inventory")renderInventory();if(page==="debts")renderDebts();if(page==="client")renderClient();if(page==="history")renderHistory()}

function renderHome(){const sm=sales.filter(x=>x.date?.startsWith(currentMonth));const total=sm.reduce((a,b)=>a+Number(b.amount||0),0);const ds=debtors(),debt=ds.reduce((a,b)=>a+b.debt,0);$("#monthSales").textContent=money(total);$("#monthSalesCount").textContent=`${sm.length} ${sm.length===1?"venta":"ventas"}`;$("#currentDebt").textContent=money(debt);$("#debtClientCount").textContent=`${ds.length} ${ds.length===1?"cliente":"clientes"}`}

function renderSaleProducts(){const sel=$("#article");if(!sel)return;const old=sel.value,items=activeInventory();sel.innerHTML='<option value="">Seleccionar artículo…</option>'+items.map(x=>`<option value="${esc(x.id)}">${esc(x.name)} — ${x.quantity} disp.</option>`).join("");if(items.some(x=>x.id===old))sel.value=old;const h=$("#articleStockHint");if(h)h.textContent=items.length?"Selecciona un producto del inventario.":"Agrega productos desde Inventario."}
async function saveSale(){const client=normName($("#clientName").value),pid=$("#article").value,prod=inventory.find(x=>x.id===pid),qty=Number.parseInt($("#saleQuantity").value,10),amount=parseAmount($("#saleAmount").value),date=$("#saleDate").value,status=$("input[name='saleStatus']:checked")?.value,out=$("#saleMessage");if(!client||!prod||!Number.isInteger(qty)||qty<=0||!amount||!date||!status){msg(out,"Completa cliente, artículo, cantidad, monto y fecha.",true);return}if(qty>Number(prod.quantity)){msg(out,`Solo hay ${prod.quantity} unidades disponibles.`,true);return}const btn=$("#saveSaleButton");btn.disabled=true;try{const saleDoc=doc(salesRef),productDoc=doc(db,"inventario",pid);await runTransaction(db,async t=>{const ps=await t.get(productDoc);if(!ps.exists())throw new Error("PRODUCT_NOT_FOUND");const stock=Number(ps.data().quantity)||0;if(qty>stock)throw new Error("INSUFFICIENT_STOCK");t.set(saleDoc,{clientName:client,clientKey:keyName(client),productId:pid,article:ps.data().name,quantity:qty,amount,status,date,createdAt:serverTimestamp()});t.update(productDoc,{quantity:stock-qty,updatedAt:serverTimestamp()})});$("#clientName").value="";$("#article").value="";$("#saleQuantity").value="";$("#saleAmount").value="";$("#saleDate").value=todayISO;$("input[name='saleStatus'][value='paid']").checked=true;msg(out,"Venta guardada e inventario actualizado.")}catch(e){console.error(e);msg(out,e.message==="INSUFFICIENT_STOCK"?"No hay suficientes unidades disponibles.":"No se pudo guardar la venta.",true)}finally{btn.disabled=false}}

function renderInventory(){const items=activeInventory();$("#inventoryProductCount").textContent=String(items.length);$("#inventoryUnitCount").textContent=String(items.reduce((s,x)=>s+Number(x.quantity||0),0));const c=$("#inventoryList");c.innerHTML=items.length?items.map(x=>`<article class="inventory-item"><div><strong>${esc(x.name)}</strong><small>${x.quantity} ${Number(x.quantity)===1?"unidad disponible":"unidades disponibles"}</small></div><div class="stock"><button data-change="-1" data-id="${esc(x.id)}">−</button><strong>${x.quantity}</strong><button data-change="1" data-id="${esc(x.id)}">+</button></div></article>`).join(""):'<p class="empty">Todavía no hay productos disponibles.</p>'}
async function addProduct(){const name=normName($("#inventoryProductName").value),q=Number.parseInt($("#inventoryProductQuantity").value,10),out=$("#inventoryMessage");if(!name||!Number.isInteger(q)||q<=0){msg(out,"Completa el producto y una cantidad válida.",true);return}const n=keyName(name),existing=inventory.find(x=>x.normalizedName===n);try{if(existing){await runTransaction(db,async t=>{const r=doc(db,"inventario",existing.id),s=await t.get(r),cur=s.exists()?Number(s.data().quantity)||0:0;t.update(r,{quantity:cur+q,updatedAt:serverTimestamp()})})}else await addDoc(inventoryRef,{name,normalizedName:n,quantity:q,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});$("#inventoryProductName").value="";$("#inventoryProductQuantity").value="";msg(out,"Inventario actualizado.")}catch(e){console.error(e);msg(out,"No se pudo guardar el producto.",true)}}
async function changeStock(id,delta){try{await runTransaction(db,async t=>{const r=doc(db,"inventario",id),s=await t.get(r);if(!s.exists())return;const cur=Number(s.data().quantity)||0;t.update(r,{quantity:Math.max(0,cur+delta),updatedAt:serverTimestamp()})})}catch(e){console.error(e)}}

function renderDebts(){const ds=debtors(),total=ds.reduce((s,x)=>s+x.debt,0);$("#debtTotalTop").textContent=money(total);$("#debtPeopleTop").textContent=`${ds.length} ${ds.length===1?"cliente":"clientes"}`;const c=$("#debtorsList");c.innerHTML=ds.length?ds.map(x=>`<article class="debtor"><div><strong>${esc(x.clientName)}</strong><small>${x.count} ${x.count===1?"venta a crédito":"ventas a crédito"}</small></div><strong class="amount">${money(x.debt)}</strong><div class="actions"><a class="smallbtn" href="client.html?client=${encodeURIComponent(x.clientKey)}">Ver detalle</a><a class="smallbtn" href="client.html?client=${encodeURIComponent(x.clientKey)}&pay=1">Registrar pago</a></div></article>`).join(""):'<p class="empty">No hay cuentas pendientes.</p>'}

let clientKeyParam=new URLSearchParams(location.search).get("client")||"";
function clientData(){const creditSales=sales.filter(x=>x.status==="credit"&&(x.clientKey||keyName(x.clientName))===clientKeyParam).sort((a,b)=>stamp(b)-stamp(a)),pays=payments.filter(x=>(x.clientKey||keyName(x.clientName))===clientKeyParam).sort((a,b)=>stamp(b)-stamp(a));const credit=creditSales.reduce((s,x)=>s+Number(x.amount||0),0),paid=pays.reduce((s,x)=>s+Number(x.amount||0),0);return{creditSales,pays,credit,paid,pending:Math.max(0,credit-paid),name:creditSales[0]?.clientName||pays[0]?.clientName||"Cliente"}}
function renderClient(){if(!clientKeyParam)return;const d=clientData();$("#clientNameTitle").textContent=d.name;$("#clientCreditTotal").textContent=money(d.credit);$("#clientPaidTotal").textContent=money(d.paid);$("#clientPendingTotal").textContent=money(d.pending);$("#clientSalesHistory").innerHTML=d.creditSales.length?d.creditSales.map(x=>`<article class="detail-row"><div><strong>${esc(x.article)}</strong><small>${x.quantity?`${x.quantity} ${Number(x.quantity)===1?"unidad":"unidades"} · `:""}${dateFmt(x.date)}</small></div><div><strong>${money(x.amount)}</strong><div class="detail-actions"><button class="textbtn edit-sale" data-id="${esc(x.id)}">Editar</button></div></div></article>`).join(""):'<p class="empty">No hay compras a crédito.</p>';$("#clientPaymentsHistory").innerHTML=d.pays.length?d.pays.map(x=>`<article class="detail-row"><div><strong>Pago recibido</strong><small>${dateFmt(x.date)}</small></div><div><strong style="color:var(--ok)">+${money(x.amount)}</strong><div class="detail-actions"><button class="textbtn edit-payment" data-id="${esc(x.id)}">Editar</button></div></div></article>`).join(""):'<p class="empty">Todavía no ha realizado pagos.</p>';$("#paymentClientLabel").textContent=`Saldo pendiente: ${money(d.pending)}`;$$('.edit-sale').forEach(b=>b.onclick=()=>openEditSale(b.dataset.id));$$('.edit-payment').forEach(b=>b.onclick=()=>openEditPayment(b.dataset.id));if(new URLSearchParams(location.search).get("pay")==="1"&&!window._autoPay){window._autoPay=true;$("#paymentPanel").classList.remove("hidden")}}
async function savePayment(){const d=clientData(),amount=parseAmount($("#paymentAmount").value),date=$("#paymentDate").value,out=$("#paymentMessage");if(!amount||!date){msg(out,"Completa monto y fecha.",true);return}if(amount>d.pending){msg(out,"El pago supera la deuda.",true);return}try{await addDoc(paymentsRef,{clientName:d.name,clientKey:clientKeyParam,amount,date,createdAt:serverTimestamp()});$("#paymentAmount").value="";msg(out,"Pago guardado.")}catch(e){console.error(e);msg(out,"No se pudo guardar el pago.",true)}}
let editSaleId=null,editPaymentId=null;
function openEditSale(id){const s=sales.find(x=>x.id===id);if(!s)return;editSaleId=id;$("#editSaleClientName").value=s.clientName||"";$("#editSaleAmount").value=new Intl.NumberFormat("es-CR").format(Number(s.amount)||0);$("#editSaleDate").value=s.date||todayISO;const sel=$("#editSaleProduct");sel.innerHTML=inventory.map(x=>`<option value="${esc(x.id)}">${esc(x.name)} — ${x.quantity} disp.</option>`).join("");if(s.productId)sel.value=s.productId;$("#editSaleQuantity").value=s.quantity||1;$("#editSaleProduct").disabled=!s.productId;$("#editSaleQuantity").disabled=!s.productId;$("#editSaleDialog").showModal()}
async function saveEditedSale(){const s=sales.find(x=>x.id===editSaleId);if(!s)return;const client=normName($("#editSaleClientName").value),amount=parseAmount($("#editSaleAmount").value),date=$("#editSaleDate").value;if(!client||!amount||!date)return msg($("#editSaleMessage"),"Completa cliente, monto y fecha.",true);try{const sr=doc(db,"ventas",s.id);if(!s.productId||!s.quantity){await runTransaction(db,async t=>t.update(sr,{clientName:client,clientKey:keyName(client),amount,date}))}else{const npid=$("#editSaleProduct").value,nq=Number.parseInt($("#editSaleQuantity").value,10),or=doc(db,"inventario",s.productId),nr=doc(db,"inventario",npid);await runTransaction(db,async t=>{const ss=await t.get(sr),os=await t.get(or),ns=npid===s.productId?os:await t.get(nr);if(!ss.exists()||!os.exists()||!ns.exists())throw new Error("NOT_FOUND");const oq=Number(ss.data().quantity)||Number(s.quantity)||0,ost=Number(os.data().quantity)||0,nst=Number(ns.data().quantity)||0;if(npid===s.productId){const avail=ost+oq;if(nq>avail)throw new Error("STOCK");t.update(or,{quantity:avail-nq,updatedAt:serverTimestamp()})}else{if(nq>nst)throw new Error("STOCK");t.update(or,{quantity:ost+oq,updatedAt:serverTimestamp()});t.update(nr,{quantity:nst-nq,updatedAt:serverTimestamp()})}t.update(sr,{clientName:client,clientKey:keyName(client),productId:npid,article:ns.data().name,quantity:nq,amount,date})})}$("#editSaleDialog").close()}catch(e){console.error(e);msg($("#editSaleMessage"),e.message==="STOCK"?"No hay suficientes unidades disponibles.":"No se pudo actualizar.",true)}}
function openEditPayment(id){const p=payments.find(x=>x.id===id);if(!p)return;editPaymentId=id;$("#editPaymentAmount").value=new Intl.NumberFormat("es-CR").format(Number(p.amount)||0);$("#editPaymentDate").value=p.date||todayISO;$("#editPaymentDialog").showModal()}
async function saveEditedPayment(){const p=payments.find(x=>x.id===editPaymentId);if(!p)return;const amount=parseAmount($("#editPaymentAmount").value),date=$("#editPaymentDate").value;if(!amount||!date)return msg($("#editPaymentMessage"),"Completa monto y fecha.",true);const credit=sales.filter(x=>x.status==="credit"&&(x.clientKey||keyName(x.clientName))===clientKeyParam).reduce((s,x)=>s+Number(x.amount),0),others=payments.filter(x=>x.id!==p.id&&(x.clientKey||keyName(x.clientName))===clientKeyParam).reduce((s,x)=>s+Number(x.amount),0);if(amount>Math.max(0,credit-others))return msg($("#editPaymentMessage"),"El pago supera la deuda pendiente.",true);try{await runTransaction(db,async t=>t.update(doc(db,"pagos",p.id),{amount,date}));$("#editPaymentDialog").close()}catch(e){console.error(e);msg($("#editPaymentMessage"),"No se pudo actualizar.",true)}}

function renderHistory(){const c=$("#historyList");const items=allMovements();if(!items.length){c.innerHTML='<p class="empty">Todavía no hay movimientos.</p>';return}const months=[...new Set(items.map(x=>x.date?.slice(0,7)).filter(Boolean))].sort().reverse();c.innerHTML=months.map(m=>{const mi=items.filter(x=>x.date?.startsWith(m)),sv=mi.filter(x=>x.kind==="sale"),pv=mi.filter(x=>x.kind==="payment");const salesHTML=sv.length?sv.map(x=>`<article class="movement"><div><strong>${esc(x.clientName)}</strong><small>${esc(x.article)}${x.quantity?` · ${x.quantity} ${Number(x.quantity)===1?"unidad":"unidades"}`:""} · ${x.status==="paid"?"Pagado":"A crédito"} · ${dateFmt(x.date)}</small></div><div><div class="moneyval sale">${money(x.amount)}</div><button class="textbtn delete-record" data-col="ventas" data-id="${esc(x.id)}">Eliminar</button></div></article>`).join(""):'<p class="empty">Sin ventas.</p>';const payHTML=pv.length?pv.map(x=>`<article class="movement"><div><strong>${esc(x.clientName)}</strong><small>Pago recibido · ${dateFmt(x.date)}</small></div><div><div class="moneyval payment">+${money(x.amount)}</div><button class="textbtn delete-record" data-col="pagos" data-id="${esc(x.id)}">Eliminar</button></div></article>`).join(""):'<p class="empty">Sin pagos.</p>';return`<section class="month-block"><div class="month-heading"><h2>${monthLabel(m)}</h2><span>${mi.length} movimientos</span></div><div class="history-section"><h3>Ventas</h3>${salesHTML}</div><div class="history-section"><h3>Pagos recibidos</h3>${payHTML}</div></section>`}).join("");$$('.delete-record').forEach(b=>b.onclick=async()=>{if(confirm("¿Eliminar este registro?"))await deleteDoc(doc(db,b.dataset.col,b.dataset.id))})}

function bind(){if(page==="sale"){$("#saleDate").value=todayISO;$("#saveSaleButton").onclick=saveSale;$("#saleAmount").onblur=e=>e.target.value=parseAmount(e.target.value)?new Intl.NumberFormat("es-CR").format(parseAmount(e.target.value)):""}if(page==="inventory"){$("#saveInventoryProductButton").onclick=addProduct;$("#inventoryList").onclick=e=>{const b=e.target.closest('[data-change]');if(b)changeStock(b.dataset.id,Number(b.dataset.change))}}if(page==="client"){$("#paymentDate").value=todayISO;$("#savePaymentButton").onclick=savePayment;$("#showPaymentButton").onclick=()=>$("#paymentPanel").classList.toggle("hidden");$("#saveEditSaleButton").onclick=saveEditedSale;$("#saveEditPaymentButton").onclick=saveEditedPayment;$("#cancelEditSaleButton").onclick=()=>$("#editSaleDialog").close();$("#cancelEditPaymentButton").onclick=()=>$("#editPaymentDialog").close()}}
bind();
onSnapshot(salesRef,s=>{sales=s.docs.map(d=>({id:d.id,...d.data()}));ready.sales=true;setStatus();render()},e=>console.error(e));
onSnapshot(paymentsRef,s=>{payments=s.docs.map(d=>({id:d.id,...d.data()}));ready.payments=true;setStatus();render()},e=>console.error(e));
onSnapshot(inventoryRef,s=>{inventory=s.docs.map(d=>({id:d.id,...d.data()}));ready.inventory=true;setStatus();render()},e=>console.error(e));
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js',{updateViaCache:'none'}).catch(console.error));
